// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrocaEndereco.Data;

namespace TrocaEndereco.Migrations
{
    [DbContext(typeof(MovimentacaoContext))]
    partial class MovimentacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrocaEndereco.Models.Endereco", b =>
                {
                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Saldo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Local");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("TrocaEndereco.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoDestino")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("EnderecoOrigem")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsgRetorno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Quantidade")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("TrocaEndereco.Models.Produto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Codigo");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
